title: 'Creating Slack Apps with Bolt Framework, NodeJS, and APIs'
description: >-
  This learning lab course is intended for the purpose of Bit Project's bootcamp
  with Slack on Slack Apps.
template:
  repo: slackapps-template
  name: slackapps
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
